### ISSUE TITLE
Adicionar ao F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [EliFUT/android#28]
Seria muito bacana ter esse app no F-Droid, que é uma espécie de Google Play mas com apenas software livre: https://f-droid.org/

Aqui tem instruções de como adicioná-lo à fila de inclusão: https://f-droid.org/contribute/

(Presumi que você fala português pelo seu nome rs)

**Comment by felipecsl** [comment]
Legal, não conhecia esse site, valeu pela dica! 👍

**Comment by pizzamaker** [comment]
@felipecsl Você enviou pra eles os metadados? Seria bacana deixar esse tíquete aberto enquanto rola o trâmite. Qualquer coisa, cê pode pingar o @krt16s, que é dev do F-Droid :)

**Comment by krt16s** [comment]
Includes non-free dependencies, like crashlytics and play-sevices. Also I don't know what gets pulled in from clojars.

**Comment by Poussinou** [comment]
@izzysoft Maybe something for your repo, since we cannot include this app in the official F-Droid repo due to crashlytics
