### ISSUE TITLE
Failed to load list of countries.

### ISSUE THREAD

**Issue by essalah** [EliFUT/android#29]
hello, how can i fix this error

"Failed to load list of countries."

**Comment by felipecsl** [comment]
I'm in the process of changing the API backend so it's unfortunately unavailable right now. I'll update this issue when it's back online

**Comment by kasatelli** [comment]
i dont know anything about ruby but i realized heroku can automatically host ruby app from github.. so i forked and did that but it didnt work.. i was getting failed to install gem via bundler

here is my log;



 !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.

			Detected buildpacks: Ruby,Node.js

			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order

-----> Ruby app detected

-----> Compiling Ruby/Rails

-----> Using Ruby version: ruby-2.3.1

-----> Installing dependencies using bundler 1.11.2

       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment

       Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

       You are trying to install in deployment mode after changing

       your Gemfile. Run `bundle install` elsewhere and add the

       updated Gemfile.lock to version control.

       You have added to the Gemfile:

       * capistrano-npm

       Bundler Output: Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

       You are trying to install in deployment mode after changing

       your Gemfile. Run `bundle install` elsewhere and add the

       updated Gemfile.lock to version control.

       

       You have added to the Gemfile:

       * capistrano-npm

 !

 !     Failed to install gems via Bundler.

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed

**Comment by felipecsl** [comment]
Yeah things are still influx in `EliFUT/backend`, been playing with it this week, but still not 100%
you may want to give it another try now, I think deployment is working already

**Comment by kasatelli** [comment]
its not.. i get "Failed to install gems via Bundler." when installing automaically via heroku/git connection... maybe i have made a mistake and because i dont know anything about ruby... can you please help me? :)

**Comment by felipecsl** [comment]
I'm not using Heroku anymore so I cant help much, been using Digital Ocean now which is much cheaper :)

**Comment by felipecsl** [comment]
check out the logs with `heroku logs` to see what failed

**Comment by kasatelli** [comment]
oooh okay, so digital ocean can host the backend easily.. i really want to biuld the project and edit the players too.. to my imaginary plaayers.... it sucks im a novice in heroku.. i will be moving to digital ocean then

**Comment by felipecsl** [comment]
you can run it wherever you want, any Linux server should do it.
Heroku is probably the easiest one to get started though. Digital Ocean will require a lot more work to set up the server and configure it.

**Comment by kasatelli** [comment]
any tutorial video suggestuons?? sorry for bothering you.. im just a complete novice.... i really wish it was a php project.. i find php easier to install :)

**Comment by felipecsl** [comment]
lol there is tons of rails tutorials and videos online. just search for ruby on rails :)

**Comment by kasatelli** [comment]
thanks

**Comment by kasatelli** [comment]
anyways, can i pay you to set it up for me on my heroku account? lol the honest fact is that im dumb and only want to play a football manager game on my android that i have control over over the backend :) lmao

**Comment by felipecsl** [comment]
This has been fixed by #30
